version: 0.0
os: linux
files:
  - source: /*.*
    destination: /tmp/codedeploy-deployment/
hooks:
  ApplicationStop:
    - location: scripts/deregister_from_elb-wrapper.sh
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
    - location: scripts/register_with_elb-wrapper.sh
      timeout: 330
      runas: root
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 200
      runas: root